name: lint

on:
  push:
  pull_request:

jobs:
  golangci:
    strategy:
      matrix:
        go: [1.19]

    name: golangci
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.50
